spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://mysql7.sqlpub.com:3312/basketball?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: user_basketball
    password: "mTQnm6mYhTDR92Uh"
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 300MB
  redis:
    host: redis-19434.c270.us-east-1-3.ec2.cloud.redislabs.com
    port: 19434
    password: "wlcdzUsh7mTE07UDjOMddeOYnGeWkfHV"
    database: 0


server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

jwt:
  secretKey: "hVg1LcycfyZCJd0YPVujGKE1KtL7ntmHEHmXFAE10jcwPRopYiVAxQcaUxB4ZKFgDUCgBxY8ujMU4ZuNuhciAjPUmWG199ztEXwy"
  expiration: 12 #???? ??

knife4j:
  enable: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yzhszgq.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  type-enums-package: com.test4.enums